In [49]:
import numpy as np
import pandas as pd

In [50]:
data=pd.read_csv('/content/insurance2.csv')

In [51]:
data.head()

age  sex     bmi  children  smoker  region      charges  insuranceclaim
0   19    0  27.900         0       1       3  16884.92400               1
1   18    1  33.770         1       0       2   1725.55230               1
2   28    1  33.000         3       0       2   4449.46200               0
3   33    1  22.705         0       0       1  21984.47061               0
4   32    1  28.880         0       0       1   3866.85520               1

In [52]:
x=data[['age','sex','bmi','children','smoker','region','charges']]
y=data['insuranceclaim']

In [53]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [54]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()

In [55]:
logmodel.fit(x_train,y_train)

LogisticRegression()

In [56]:
y_pred=logmodel.predict(x_test)

In [57]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)

In [58]:
print(cm)

[[ 77  44]
 [ 22 125]]


In [59]:
print(ac)

0.753731343283582


In [60]:
new_data={'age':25,'sex':1,'bmi':28.5,'children':0,'smoker':1,'region':3,'charges':100}

In [61]:
index=[1]
my_data=pd.DataFrame(new_data,index)

In [62]:
print(my_data)

   age  sex   bmi  children  smoker  region  charges
1   25    1  28.5         0       1       3      100


In [63]:
y_pred=logmodel.predict(my_data)

In [64]:
print(y_pred)

[1]


USING KNN ALGORITHM

In [65]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier=KNeighborsClassifier(n_neighbors=7)

In [66]:
knn_classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [67]:
k_pred=knn_classifier.predict(x_test)

In [68]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test,k_pred)
ac=accuracy_score(y_test,k_pred)

In [69]:
print(cm)

[[ 55  66]
 [ 26 121]]


In [70]:
print(ac)

0.6567164179104478


USING DECISION TREE ALGORITHM

In [71]:
from sklearn.tree import DecisionTreeClassifier
tree_classify=DecisionTreeClassifier()

In [72]:
tree_classify.fit(x_train,y_train)

DecisionTreeClassifier()

In [73]:
d_pred=tree_classify.predict(x_test)

In [74]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test,d_pred)
ac=accuracy_score(y_test,d_pred)

In [75]:
print(cm)

[[120   1]
 [  3 144]]


In [76]:
print(ac)

0.9850746268656716


USING RANDOM FOREST ALGORITHM

In [77]:
from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier()

In [78]:
forest.fit(x_train,y_train)

RandomForestClassifier()

In [79]:
f_pred=forest.predict(x_test)

In [80]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test,f_pred)
ac=accuracy_score(y_test,f_pred)

In [81]:
print(cm)

[[115   6]
 [  9 138]]


In [82]:
print(ac)

0.9440298507462687
